import type { Metadata } from "next";
import PageHero from "@/components/PageHero/PageHero";

export const metadata: Metadata = {
  title: "Terms and Conditions | TIMS Education",
  description: "Terms of Use and Conditions for accessing and using the TIMS Education platform and services.",
};

export default function TermsAndConditionsPage() {
  return (
    <main>
      <PageHero title="Terms & Conditions" />
      <section
        style={{
          padding: "clamp(3rem, 6vw, 5rem) 1.5rem",
          background: "#faf8f3",
          minHeight: "60vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "flex-start",
        }}
      >
        <div
          style={{
            maxWidth: "900px",
            width: "100%",
            background: "#ffffff",
            border: "3px solid #14161c",
            borderRadius: "18px",
            padding: "clamp(2rem, 4vw, 3.5rem)",
            boxShadow: "6px 6px 0 #14161c",
            lineHeight: 1.85,
            color: "#374151",
            fontSize: "0.95rem",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "1.5rem" }}>
            <span
              style={{
                display: "inline-block",
                padding: "0.35rem 0.85rem",
                borderRadius: "20px",
                background: "#eff6ff",
                color: "#2563eb",
                border: "1.5px solid #3b82f6",
                fontSize: "0.8125rem",
                fontWeight: 800,
                textTransform: "uppercase",
                letterSpacing: "0.05em",
              }}
            >
              Legal Terms
            </span>
          </div>

          <p style={{ marginBottom: "1.25rem" }}>
            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <p style={{ marginBottom: "1.25rem" }}>
            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name TIMS EDUCATION (&apos;Website&apos;), including the related mobile site and mobile application (hereinafter referred to as &apos;Platform&apos;).
          </p>

          <p style={{ marginBottom: "1.25rem" }}>
            The Platform is owned by <strong style={{ color: "#14161c" }}>TIMS EDUCATION</strong>, an institution with its office at 2nd Floor, Pamls Tower, near Central Bank, Thazhepalam, Tirur, Kerala 676101.
          </p>

          <p style={{ marginBottom: "1.5rem" }}>
            Your use of the Platform and services and tools are governed by the following terms and conditions (&apos;Terms of Use&apos;) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, &apos;Services&apos;). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
          </p>

          <div
            style={{
              background: "#fff1f2",
              borderLeft: "4px solid #e11d48",
              padding: "1rem 1.25rem",
              borderRadius: "8px",
              fontWeight: 700,
              color: "#9f1239",
              marginBottom: "1.75rem",
              fontSize: "0.9rem",
              letterSpacing: "0.02em",
            }}
          >
            ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
          </div>

          <h3 style={{ fontSize: "1.15rem", fontWeight: 800, color: "#14161c", marginBottom: "1rem" }}>
            General Provisions &amp; Usage Rules
          </h3>

          <ul style={{ paddingLeft: "1.25rem", margin: "0 0 1.5rem", display: "flex", flexDirection: "column", gap: "1rem" }}>
            <li>
              To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
            </li>
            <li>
              Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
            </li>
            <li>
              Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.
            </li>
            <li>
              The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.
            </li>
            <li>
              You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.
            </li>
            <li>
              You agree to pay us the charges associated with availing the Services.
            </li>
            <li>
              You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.
            </li>
            <li>
              You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience to provide further information.
            </li>
            <li>
              You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
            </li>
            <li>
              You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney&apos;s fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
            </li>
            <li>
              Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
            </li>
            <li>
              These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
            </li>
            <li>
              All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Kochi.
            </li>
            <li>
              All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
            </li>
          </ul>
        </div>
      </section>
    </main>
  );
}
